# @package _global_
defaults:
  - /ablations/nemo3d_align/app_dist_cyclic_temp/_default

ablation_name_nemo3d_align_sem_dist_cyclic_temp: sem_cyclic_temp_1000

method:
  nemo:
    sem_cyclic_weight_temp: 1000.
