# @package _global_
defaults:
  - /ablations/nemo3d_align/mesh@: _default

ablation_name: dinov2_convex500

mesh_name: 'convex500' # 'convex500', 'voxel500' 'poisson500', 'alpha500'

train_datasets:
  labeled:
    mesh_name: ${mesh_name}
    preprocess:
      mesh:
        enabled: True
test_datasets:
  co3d:
    mesh_name: ${mesh_name}
    preprocess:
      mesh:
        enabled: True