# @package _global_

categories:
#  - bicycle
#  - truck
#  - train
#  - teddybear
#  - car
#  - bus
#  - motorcycle
#  - keyboard
#  - handbag
#  - remote
#  - airplane
#  - toilet
#  - hairdryer
#  - mouse
#  - toaster
#  - hydrant
#  - chair
#  - laptop
#  - book
  - backpack
