- car
- apple
- backpack
- ball
- banana
- baseballbat
- baseballglove
- bench
- bicycle
- book
- bottle
- bowl
- broccoli
- cake
- car
- carrot
- cellphone
- chair
- couch
- cup
- donut
- frisbee
- hairdryer
- handbag
- hotdog
- hydrant
- keyboard
- kite
- laptop
- microwave
- motorcycle
- mouse
- orange
- parkingmeter
- pizza
- plant
- remote
- sandwich
- skateboard
- stopsign
- suitcase
- teddybear
- toaster
- toilet
- bus
- airplane
- train
- truck
- tv
- umbrella
- vase
- wine_glass

# these are the universal OD3D names
