# @package _global_
ablation_name: inference_mask_object_ransac_add_texture

method:
    nemo:
        checkpoint: ${platform.path_exps}/08-08_17-27-08_CO3D_NeMo_uniform_train_co3d_3s_slurm/nemo.ckpt

        test:
          transform:
            apply_txtr: True
            config: ${texture_dataset}

train: False
test: True
