# @package _global_
defaults:
  - /ablations/architecture/_default

ablation_name_architecture: 'head_resnet_no_temp'

method:
  nemo:
    train:
      T: 1.
    model:
      head:
        normalize: False