# @package _global_

ablation_name_nemo3d_align_cuboid_refine: aligned_uniform
ablation_name: ${ablation_name_nemo3d_align_cuboid_refine}

method:
  nemo:
    inference:
      use_mask_object: True
      sample:
        method: uniform # epnp3d2d uniform
        epnp3d2d:
          count_cams: 100
          count_pts: 4
        uniform:
          azim:
            min: '0.'
            max: math.pi * 2 / 8.                 # math.pi * 2 - (math.pi * 2) / 12. # 12
            steps: 8               #  12
          elev:
            min: -math.pi / 2 + math.pi / 8  #-math.pi / 6
            max: math.pi / 2  - math.pi / 8 # math.pi / 3
            steps: 4

          theta:
            min: -math.pi + math.pi / 8 # -math.pi / 6
            max: math.pi - math.pi / 8 # math.pi / 6
            steps: 4
      refine:
        enabled: True
        dims_detached: [0, 1, 2] # 0-5, transl: 0, 1, 2, rot: 3, 4, 5
    train:
      epochs: 10
    test:
      transform:
        class_name: CenterZoom3D
        W: 512
        H: 512
        scale:
        scale_with_mask: 1.
        center_rel_shift_xy:
          - -0.
          - -0.