# mkdir /misc/lmbraid19/sommerl/datasets/Objectron
# gsutil -m cp -n -r gs://objectron/v1/records_shuffled /misc/lmbraid19/sommerl/datasets/Objectron


name: objectron
class_name: Objectron

modalities:
    - 'size'
    - 'category'
    - 'cam_intr4x4'
    - 'cam_tform4x4_obj'
    - 'category'
    - 'rgb'
    - 'mask'
    - 'sequence_name'
    - 'sequence'
    # - 'mesh'
#
#mesh_name: 'alpha500' # 'convex500', 'voxel500' 'poisson500', 'alpha500'
#pcl_source: 'droid_slam_clean'
#
#cuboid_source: 'droid_slam' #'kpts2d_orient_and_pcl', 'front_frame_and_pcl', 'limits3d', 'droid_slam'
#cam_tform_obj_source: 'droid_slam'  # 'kpts2d_orient_and_pcl' #'kpts2d_orient_and_pcl', 'front_frame_and_pcl', 'first_frame', 'front_frame', 'limits3d', 'droid_slam'
#
#mesh_feats_type: 'M_dinov2_frozen_base_T_centerzoom512_R_acc' # 'R_acc' # 'R_avg', 'R_avg_norm'
#dist_verts_mesh_feats_reduce_type: 'min' # 'avg', 'min'
#
#frames_count_max_per_sequence:
#block_negative_depth: False

path_raw: ${platform.path_datasets_raw}/Objectron
path_preprocess: ${platform.path_datasets_preprocess}/Objectron_Preprocess

setup:
  enabled: False
  override: False
  remove_previous: False

extract_meta:
  enabled: False
  override: False
  remove_previous: False


#preprocess:
#  label:
#    enabled: False
#    override: False
#  droid_slam:
#    enabled: False
#    override: False
#  pcl:
#    enabled: False
#    override: False
#    remove_previous: False
#  mesh:
#    enabled: False
#    override: False
#  mesh_feats:
#    enabled: False
#    override: False
#  cuboid:
#    enabled: False
#    override: False
#    remove_previous: False
#  cuboid_avg:
#    enabled: False
#    override: False
#    remove_previous: False
