defaults:
  - logger: wandb
  - methods@method.nemo: nemo_align3d
  - methods/dataset@method.nemo: co3d
  - datasets@train_datasets.src: co3d_no_zsp_5s_labeled_ref # co3d_no_zsp_5s_labeled_ref, co3dv1_zsp_10s, co3d_no_zsp_50s_unlabeled
  - datasets@train_datasets.labeled: co3d_no_zsp_5s_labeled_ref # co3d_no_zsp_5s_labeled_ref, co3dv1_zsp_10s, co3d_no_zsp_50s_unlabeled
  - datasets@val_datasets.main:
  - datasets@test_datasets.co3d: co3d_no_zsp_5s_labeled_ref # co3d_no_zsp_5s_labeled_ref, co3dv1_zsp_10s, co3d_no_zsp_50s_unlabeled
  - platform@platform_local: local
  - datasets@texture_dataset: dtd
  - platform: local
  - _self_

seed_number: 0

categories:
  - bicycle
  - truck
  - train
  - teddybear
  - car
  - bus
  - motorcycle
  - keyboard
  - handbag
  - remote
  - airplane
  - toilet
  - hairdryer
  - mouse
  - toaster
  - hydrant
  - chair
  - laptop
  - book
  - backpack
  - cellphone # from cellphone on, no zsp categories
  - microwave
  - bench
  - bottle
  - couch
  - cup
  - suitcase
  - tv

metrics:
  - metricA
  - metricB

mesh_feats_type: 'M_dinov2_vits14_frozen_base_no_norm_T_centerzoom512_R_acc'
# M_dinov2_vitb14_frozen_base_no_norm_T_centerzoom512_R_acc
# M_dinov2_vits14_frozen_base_no_norm_T_centerzoom512_R_acc
# M_dino_vits8_frozen_base_no_norm_T_centerzoom512_R_acc
#  'R_acc' # 'R_avg', 'R_avg_norm', 'R_min50'
mesh_type: 'alpha500' # 'alphawrap500' 'alpha500' 'convex500', 'voxel500' 'poisson500', 'alpha500'
mesh_feats_dist_reduce_type: 'min_avg' # 'pca32_', 'avg', 'min', 'min_avg'
aligned_name: '${mesh_type}_dinov2s' # 'alpha500_dinov2s_test' # 'alphawrap500_dinov2b' 'latest_50s_to_5s_sota' # _sota_ref_86_64

method:
  nemo:
    refine_optimization_steps: 0 # 20
    refine_lr: 2e-2 # 2e-2
    refine_pts_weight: 0. # 0.5 # 0.1 too small, 1 too large
    refine_arap_weight: 1. # 1.
    refine_reg_weight: 0. # 0.1
    refine_arap_geo_std: 0.05 # 0.05 - 0.1

    ransac:
      samples: 1000
      score_perc: 1.
    use_only_first_reference: False
    geo_cyclic_weight_temp: 0.9  # 0.9
    app_cyclic_weight_temp: 0.9  # 0.9
    gt_cam_tform_obj_source: labeled_cuboid # zsp_labeled, labeled, labeled_cuboid or '' for only align
    dist_appear_weight: 0.2
    global_optimization_steps: 1
    categories: ${categories}
    aligned_name: ${aligned_name}

    preprocess:
      pcl:
        enabled: True
        override: False
      tform_obj:
        enabled: True
        override: False
      mesh:
        enabled: True
        override: False
      mesh_feats:
        enabled: True
        override: False
      mesh_feats_dist:
        enabled: True
        override: False


train_datasets:
  src:
    #preprocess: ${preprocess}
    mesh_type: ${mesh_type}
    mesh_feats_type: ${mesh_feats_type}
    mesh_feats_dist_reduce_type: ${mesh_feats_dist_reduce_type}
    categories: ${categories}
  labeled:
    #preprocess: ${preprocess}
    mesh_type: ${mesh_type}
    mesh_feats_type: ${mesh_feats_type}
    mesh_feats_dist_reduce_type: ${mesh_feats_dist_reduce_type}
    categories: ${categories}

val_datasets:
  main:
    #preprocess: ${preprocess}
    mesh_type: ${mesh_type}
    mesh_feats_type: ${mesh_feats_type}
    mesh_feats_dist_reduce_type: ${mesh_feats_dist_reduce_type}
    categories: ${categories}

test_datasets:
  co3d:
    #preprocess: ${preprocess}
    mesh_type: ${mesh_type}
    mesh_feats_type: ${mesh_feats_type}
    mesh_feats_dist_reduce_type: ${mesh_feats_dist_reduce_type}
    categories: ${categories}

train: True
test: True

