# @package _global_
defaults:
  - /ablations/score/batch_size/_default

ablation_name_score_batch_size: 'bs16x12'

method:
  nemo:
    train:
      batch_accumulate_to_next_step: 16
      dataloader:
        batch_size: 12 # 12, artur: 24/32 wufei: 108