# @package _global_

method:
  nemo:
    #checkpoint: ${platform.path_exps}/01-25_23-04-01_Pascal3D_NeMo_von_mises_fisher_no_normalize_slurm/nemo.ckpt
    bank_feats_normalize: False
    bank_feats_distribution: 'von-mises-fisher' # 'von-mises-fisher', 'gaussian'
    train:
      T: 1.
    model:
      head:
        normalize: False