
train:
    epochs: 20
    dataloader:
        num_workers: 4
        batch_size: 12
        pin_memory: True

test:
    dataloader:
        num_workers: 1
        batch_size: 1
        pin_memory: True