# @package _global_
defaults:
  - /ablations/tom/_default
  - override /methods/model@method.nemo.model: resnet50_unfrozen

ablation_name_tom: 'backbone_resnet_unfrozen_moving_avg'

method:
  nemo:
#    inference:
#      pre_rendered: False
#    test:
#      dataloader:
#        batch_size: 2 # 4,
    train:
#      batch_accumulate_to_next_step: 2
#      dataloader:
#        batch_size: 12 # 12, artur: 24/32 wufei: 108
      bank_feats_update: moving_average # loss_gradient, normalize_loss_gradient, moving_average, loss
      alpha: 0.96