# @package _global_

mesh_feats_type: 'M_dino_vits8_frozen_base_T_centerzoom512_R_acc' # 'R_acc' # 'R_avg', 'R_avg_norm'

aligned_name: '${mesh_type}_dinov1s_ref' # 'alpha500_dinov2s_test' # 'alphawrap500_dinov2b' 'latest_50s_to_5s_sota' # _sota_ref_86_64




