# @package _global_

mesh_feats_type: 'M_resnet50_frozen_base_no_norm_T_centerzoom512_R_acc_ref' # 'R_acc' # 'R_avg', 'R_avg_norm'

aligned_name: '${mesh_type}_resnet50_ref' # 'alpha500_dinov2s_test' # 'alphawrap500_dinov2b' 'latest_50s_to_5s_sota' # _sota_ref_86_64
