# @package _global_
defaults:
  - /ablations/nemo_backbone@: _default
  - override /methods/model@method.nemo.model: resnet50_frozen

ablation_name: resnet50_frozen

method:
  nemo:
    checkpoint: ${platform.path_exps}/08-31_18-25-27_Pascal3D_NeMo_resnet50_frozen_slurm/nemo.ckpt

