# @package _global_
defaults:
  - override /datasets@train_dataset: co3d_55s_train #  co3d_55s_train, pascal3d_train

ablation_name: ransac_train_co3d_55s

method:
    nemo:
        inference:
            sample:
                method: epnp3d2d # epnp3d2d uniform
            optimizer:
                beta0: 0.4
                beta1: 0.6
                lr: 2e-2 # 5e-3 5e-2
                epochs: 30 # 30
        test:
            transform:
                W: 800 # 800 512
                H: 640 # 640 512
                dist: 25. # 5. (scale_normalized_to_real) * 5. (default distance used)
                center3d: [ 0., 0., 0. ] #  None
train: True
test: True