defaults:
  - dinov2_vitb14_frozen_base

backbone:
  hub_model: 'dinov2_vits14' # dino_vits8, dino_vitb8, dino_vits16, dino_vitb16, dinov2_vits14, dinov2_vitb14, dinov2_vitl14, dinov2_vitg14

head:
  normalize: False

