# @package _global_
ablation_name: ransac_aug_color_dist_center

method:
    nemo:
      checkpoint: ${platform.path_exps}/07-25_13-49-09_CO3D_NeMo_aug_color_dist_center_slurm/nemo.ckpt
      inference:
        sample:
          method: epnp3d2d # epnp3d2d uniform
      train:
        epoch: 5
        transform:
          random_color: True
          random_center_zoom3d:
            W: 512
            H: 512
            dist_min: 5.
            dist_max: 15.
            center3d_min:
                - -0.5
                - -0.5
                - -0.5
            center3d_max:
                - +0.5
                - +0.5
                - +0.5
        test:
            transform:
                W: 512 # 800 512
                H: 512 # 640 512
                dist: 25. # 5. (scale_normalized_to_real) * 5. (default distance used)
                center3d: [ 0., 0., 0. ] #  None

train: False
test: True
