# @package _global_
defaults:
  - /ablations/score/mask/_default

ablation_name_score_mask: 'mask_train'

method:
  nemo:
    train:
      use_mask_object: True
    inference:
      use_mask_object: False