# @package _global_
defaults:
  - /ablations/score/mask/_default

ablation_name_score_mask: 'no_mask'

method:
  nemo:
    train:
      use_mask_object: False
    inference:
      use_mask_object: False